name=str(input("Enter your name here= "))
num1=float(input("Enter a number here="))
num2=float(input("Enter a number here="))
print("Hello ",name," here are oparations for your given numbers.")
a=("addtion=",num1+num2)
s=("subtration=",num1-num2)
m=("multiplication=",num1*num2)
d=("division=",num1/num2)
print(a,s,m,d)